# fly.toml app configuration file generated for ares-xzy-gq on 2026-07-15T07:15:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ares-xzy-gq'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Asia/Kolkata'

[[vm]]
  memory = '768mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 768
  processes = ['app']
  size = 'shared-cpu-1x'

[restart]
  policy = 'never'
