# fly.toml app configuration file generated for ares-xzy-gq on 2026-05-11T05:36:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ares-xzy-gq'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  TZ = 'Asia/Kolkata'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
