# fly.toml app configuration file generated for ares-trading-system on 2026-04-29T13:50:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ares-trading-system-v2'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
