from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Tuple, Optional, Dict, Any
import random

def confidence_from_score(score: int, max_score: int) -> str:
    """
    Standardized confidence banding shared by all detectors (TASK-172, audit
    items 12/19): a setup is HIGH confidence when it scores at least 60% of its
    detector's score matrix, MEDIUM otherwise. Previously each detector used
    its own inconsistent bar (breakout 4/6, OI wall and exhaustion 2/4).
    """
    if max_score <= 0:
        return "MEDIUM"
    return "HIGH" if (score / max_score) >= 0.6 else "MEDIUM"


class SetupType(Enum):
    """
    Defines the core setups detected by the ARES system.
    
    Attributes:
        FAILED_BREAKOUT: Triggered when price breaches a level but fails to sustain.
        OI_WALL_REJECTION: Triggered by rejection at strikes with massive fresh Open Interest.
        EXHAUSTION_REVERSAL: Triggered by volume climaxes and indecision at price extremes.
        TREND_CONTINUATION: Triggered by a shallow pullback and resumption within a persistent regime.
    """
    FAILED_BREAKOUT = "FAILED_BREAKOUT"
    OI_WALL_REJECTION = "OI_WALL_REJECTION"
    EXHAUSTION_REVERSAL = "EXHAUSTION_REVERSAL"
    TREND_CONTINUATION = "TREND_CONTINUATION"


class Direction(Enum):
    """
    Indicates the directional bias of the detected trading signal.
    """
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"


@dataclass
class OHLCVCandle:
    """
    Represents a single 1-minute price candle for NIFTY 50.
    Includes OHLCV data along with an incrementally calculated VWAP.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float = 0.0


@dataclass
class OptionRow:
    """
    Represents a single option contract (CE or PE) at a specific strike price.
    Contains critical data such as Open Interest (OI), Implied Volatility (IV), and the Greeks.
    This structure is vital for detecting OI walls and IV crushes.
    """
    strike: int
    option_type: str  # "CE" or "PE"
    ltp: float
    iv: float
    oi: int
    oi_prev: int
    oi_change_pct: float
    gamma: float = 0.0
    theta: float = 0.0
    delta: float = 0.0
    vega: float = 0.0


@dataclass
class ATMStrikes:
    """
    Holds the current At-The-Money (ATM) context for NIFTY 50.
    Stores the spot price and the nearest CE and PE OptionRow data,
    allowing the system to make decisions based on the most liquid options.
    """
    spot_price: float
    ce: OptionRow
    pe: OptionRow


@dataclass
class ResistanceLevel:
    """
    Represents a significant price level on the chart that acts as support or resistance.
    These levels are built from sources like Previous Day High/Low (PDH/PDL) or massive OI walls.
    """
    price: float
    source: str
    strength: int  # 1 to 3, representing the importance/confidence of the level


@dataclass
class AresSignal:
    """
    The complete trade signal package generated by the ARES Engine.
    
    Attributes:
        setup_type: The strategy that triggered the signal.
        direction: Bullish (CE) or Bearish (PE).
        trigger_price: The spot price at the time of signal generation.
        entry_zone: The suggested price range for trade entry.
        stop_loss: The invalidation level for the trade (Spot reference).
        target_1: First profit target based on structural support/resistance.
        target_2: Second profit target based on further structural levels.
        confidence: Signal quality assessment (HIGH or MEDIUM).
        reasons: Detailed list of technical conditions that met the trigger.
        timestamp: Exact time the signal was generated.
        strike_to_trade: The recommended option strike price.
        option_type: The recommended option contract type (CE/PE).
    """
    setup_type: SetupType
    direction: Direction
    trigger_price: float
    entry_zone: Tuple[float, float]
    stop_loss: float
    target_1: float
    target_2: float
    confidence: str
    reasons: List[str]
    timestamp: datetime
    strike_to_trade: int
    option_type: str
    signal_id: str = field(default_factory=lambda: f"{random.randint(0, 9999):04d}")
    db_id: Optional[int] = None  # ares_signals row id, set after log_signal; joins trade_analytics to ares_signals
    suggested_lots: Optional[int] = None
    option_sl: Optional[float] = None
    option_target: Optional[float] = None
    capital: Optional[float] = None
    option_delta: Optional[float] = None
    option_premium: Optional[float] = None
    risk_pct: Optional[float] = None
    oi_wall_context: Optional[Dict[str, Any]] = None


@dataclass(frozen=True)
class OIWallBias:
    """
    Directional bias and persistent state identified by OIWallDetector.
    Observation only — does not create trade signals directly.
    """
    wall_key: str                         # stable key: f"{wall_option_type}:{int(strike)}"
    wall_strike: float
    wall_option_type: str                 # "CE" or "PE"
    direction: Direction                  # CE wall -> BEARISH; PE wall -> BULLISH
    trade_option_type: str                # CE for bullish, PE for bearish
    wall_oi: int
    wall_oi_change_pct: float
    relative_percentile: Optional[float] # 0..100 among non-zero same-side strikes
    first_seen: datetime
    last_seen: datetime
    persistence_snapshots: int
    persistence_duration_seconds: float
    state: str                            # TRACKING | PERSISTENT | INTERACTED | RETEST_READY | EXPIRED | CONSUMED
    initial_interaction_timestamp: Optional[datetime]
    initial_interaction_price: Optional[float]
    favourable_excursion_pts: float
    reasons: Tuple[str, ...]


@dataclass(frozen=True)
class OIWallTelemetry:
    """
    Normalized telemetry contract for Supabase persistence and ML collection.
    """
    bias: Optional[OIWallBias]
    entry_status: str                     # NO_WALL | WAITING | QUALIFIED | EXPIRED | CONSUMED
    filter_state: Optional[str]           # TRACKING | PERSISTENT | INTERACTED | RETEST_READY | QUALIFIED | CONSUMED | EXPIRED | NO_WALL
    rejection_reason: Optional[str]       # Specific rejection/expiration reason or None
    initial_interaction_timestamp: Optional[datetime]
    initial_interaction_price: Optional[float]
    favourable_excursion_pts: Optional[float]
    retest_timestamp: Optional[datetime]
    reference_price: Optional[float]
    vwap: Optional[float]                 # Intraday VWAP from candle context when available
    opening_range: Optional[Dict[str, Optional[float]]]

    def to_dict(self) -> Dict[str, Any]:
        if self.bias is None or self.entry_status == "NO_WALL":
            return {}
        from storage import to_utc_iso
        return {
            "wall_key": self.bias.wall_key,
            "wall_strike": self.bias.wall_strike,
            "wall_option_type": self.bias.wall_option_type,
            "direction": self.bias.direction.value,
            "trade_option_type": self.bias.trade_option_type,
            "wall_oi": self.bias.wall_oi,
            "wall_oi_change_pct": self.bias.wall_oi_change_pct,
            "relative_percentile": self.bias.relative_percentile,
            "persistence_snapshots": self.bias.persistence_snapshots,
            "persistence_duration_seconds": self.bias.persistence_duration_seconds,
            "initial_interaction_timestamp": to_utc_iso(self.initial_interaction_timestamp) if self.initial_interaction_timestamp else None,
            "initial_interaction_price": self.initial_interaction_price,
            "favourable_excursion_pts": self.favourable_excursion_pts,
            "entry_status": self.entry_status,
            "filter_state": self.filter_state,
            "rejection_reason": self.rejection_reason,
            "retest_timestamp": to_utc_iso(self.retest_timestamp) if self.retest_timestamp else None,
            "reference_price": self.reference_price,
            "vwap": self.vwap,
            "opening_range": self.opening_range,
        }


@dataclass(frozen=True)
class OIWallEntryDecision:
    """
    Deterministic entry filter evaluation returned on every candle.
    """
    status: str                           # NO_WALL | WAITING | QUALIFIED | EXPIRED | CONSUMED
    wall_key: Optional[str]
    decision_id: Optional[str]
    bias: Optional[OIWallBias]             # latest filter-owned bias state
    telemetry: OIWallTelemetry             # same-cycle state for engine/main/collector
    trigger_price: Optional[float]
    retest_timestamp: Optional[datetime]
    rejection_reason: Optional[str]
    reference_price: Optional[float]
