from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Tuple

class SetupType(Enum):
    """
    Defines the core setups detected by the ARES system.
    
    Attributes:
        FAILED_BREAKOUT: Triggered when price breaches a level but fails to sustain.
        OI_WALL_REJECTION: Triggered by rejection at strikes with massive fresh Open Interest.
        EXHAUSTION_REVERSAL: Triggered by volume climaxes and indecision at price extremes.
    """
    FAILED_BREAKOUT = "FAILED_BREAKOUT"
    OI_WALL_REJECTION = "OI_WALL_REJECTION"
    EXHAUSTION_REVERSAL = "EXHAUSTION_REVERSAL"


class Direction(Enum):
    """
    Indicates the directional bias of the detected trading signal.
    """
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"


@dataclass
class OHLCVCandle:
    """
    Represents a single 1-minute price candle for NIFTY 50.
    Includes OHLCV data along with an incrementally calculated VWAP.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float = 0.0


@dataclass
class OptionRow:
    """
    Represents a single option contract (CE or PE) at a specific strike price.
    Contains critical data such as Open Interest (OI), Implied Volatility (IV), and the Greeks.
    This structure is vital for detecting OI walls and IV crushes.
    """
    strike: int
    option_type: str  # "CE" or "PE"
    ltp: float
    iv: float
    oi: int
    oi_prev: int
    oi_change_pct: float
    gamma: float = 0.0
    theta: float = 0.0


@dataclass
class ATMStrikes:
    """
    Holds the current At-The-Money (ATM) context for NIFTY 50.
    Stores the spot price and the nearest CE and PE OptionRow data,
    allowing the system to make decisions based on the most liquid options.
    """
    spot_price: float
    ce: OptionRow
    pe: OptionRow


@dataclass
class ResistanceLevel:
    """
    Represents a significant price level on the chart that acts as support or resistance.
    These levels are built from sources like Previous Day High/Low (PDH/PDL) or massive OI walls.
    """
    price: float
    source: str
    strength: int  # 1 to 3, representing the importance/confidence of the level


@dataclass
class AresSignal:
    """
    The complete trade signal package generated by the ARES Engine.
    
    Attributes:
        setup_type: The strategy that triggered the signal.
        direction: Bullish (CE) or Bearish (PE).
        trigger_price: The spot price at the time of signal generation.
        entry_zone: The suggested price range for trade entry.
        stop_loss: The invalidation level for the trade (Spot reference).
        target_1: First profit target based on structural support/resistance.
        target_2: Second profit target based on further structural levels.
        confidence: Signal quality assessment (HIGH or MEDIUM).
        reasons: Detailed list of technical conditions that met the trigger.
        timestamp: Exact time the signal was generated.
        strike_to_trade: The recommended option strike price.
        option_type: The recommended option contract type (CE/PE).
    """
    setup_type: SetupType
    direction: Direction
    trigger_price: float
    entry_zone: Tuple[float, float]
    stop_loss: float
    target_1: float
    target_2: float
    confidence: str
    reasons: List[str]
    timestamp: datetime
    strike_to_trade: int
    option_type: str
