from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Tuple

class SetupType(Enum):
    """
    Defines the three core setups detected by the ARES system.
    
    - FAILED_BREAKOUT: Price crosses a level but fails to hold.
    - OI_WALL_REJECTION: Price bounces or rejects from a strike with massive fresh OI.
    - EXHAUSTION_REVERSAL: Volume climax with a doji-like candle at a market extreme.
    """
    FAILED_BREAKOUT = "FAILED_BREAKOUT"
    OI_WALL_REJECTION = "OI_WALL_REJECTION"
    EXHAUSTION_REVERSAL = "EXHAUSTION_REVERSAL"


class Direction(Enum):
    """
    Indicates the directional bias of the detected trading signal.
    """
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"


@dataclass
class OHLCVCandle:
    """
    Represents a single 1-minute price candle for NIFTY 50.
    Includes OHLCV data along with an incrementally calculated VWAP.
    """
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    vwap: float = 0.0


@dataclass
class OptionRow:
    """
    Represents a single option contract (CE or PE) at a specific strike price.
    Contains critical data such as Open Interest (OI), Implied Volatility (IV), and the Greeks.
    This structure is vital for detecting OI walls and IV crushes.
    """
    strike: int
    option_type: str  # "CE" or "PE"
    ltp: float
    iv: float
    oi: int
    oi_prev: int
    oi_change_pct: float
    gamma: float = 0.0
    theta: float = 0.0


@dataclass
class ATMStrikes:
    """
    Holds the current At-The-Money (ATM) context for NIFTY 50.
    Stores the spot price and the nearest CE and PE OptionRow data,
    allowing the system to make decisions based on the most liquid options.
    """
    spot_price: float
    ce: OptionRow
    pe: OptionRow


@dataclass
class ResistanceLevel:
    """
    Represents a significant price level on the chart that acts as support or resistance.
    These levels are built from sources like Previous Day High/Low (PDH/PDL) or massive OI walls.
    """
    price: float
    source: str
    strength: int  # 1 to 3, representing the importance/confidence of the level


@dataclass
class AresSignal:
    """
    The final output object generated by the ARES Engine when a setup triggers.
    Contains everything needed to send an actionable Discord alert and to log
    the trade securely into Supabase for review.
    """
    setup_type: SetupType
    direction: Direction
    trigger_price: float
    entry_zone: Tuple[float, float]
    stop_loss: float
    target_1: float
    target_2: float
    confidence: str  # "HIGH" or "MEDIUM"
    reasons: List[str]
    timestamp: datetime
    strike_to_trade: int
    option_type: str  # "CE" or "PE"
