"""
Trade Simulator
===============

Simulates trade execution on historical data based on ARES signals.
Handles entry, stop-loss, target exits, and end-of-day forced closure.

Each signal produces a CompletedTrade with full P&L accounting.
No look-ahead bias: only data available at signal time + future candles
are used for exit determination.
"""

from dataclasses import dataclass, field
from datetime import datetime, time as dtime
from typing import List, Optional, Tuple

import numpy as np
import pandas as pd

from models import AresSignal, Direction


@dataclass
class CompletedTrade:
    """
    A fully resolved trade with entry, exit, and P&L information.
    
    Attributes:
        signal:          The original AresSignal that triggered the trade.
        entry_price:     The price at which the trade was entered.
        exit_price:      The price at which the trade was exited.
        exit_reason:     Why the trade was closed: 'SL', 'T1', 'T2', 'EOD'.
        pnl_points:      Profit/loss in NIFTY spot points.
        entry_time:      Timestamp of entry.
        exit_time:       Timestamp of exit.
        holding_candles: Number of candles the trade was held.
        peak_favorable:  Maximum favorable excursion in points.
        peak_adverse:    Maximum adverse excursion in points (always positive).
    """
    signal: AresSignal
    entry_price: float
    exit_price: float
    exit_reason: str
    pnl_points: float
    entry_time: datetime
    exit_time: datetime
    holding_candles: int
    peak_favorable: float = 0.0
    peak_adverse: float = 0.0


class TradeSimulator:
    """
    Simulates trade execution on historical candle data.
    
    Assumptions:
      - Entry occurs at the signal's trigger_price on the candle immediately
        following the signal candle.
      - Exits are checked candle-by-candle: SL first, then T2, then T1.
        Priority: SL > T2 > T1 (worst case checked first to avoid bias).
      - If the session ends (15:25 IST) with an open position, it is closed
        at the last candle's close.
      - No slippage or commission by default (can be configured).
    """

    def __init__(
        self,
        slippage_pts: float = 0.0,
        commission_pts: float = 0.0,
        eod_exit_time: dtime = dtime(15, 25),
    ):
        """
        Args:
            slippage_pts:   Points of slippage to add to entry cost.
            commission_pts: Points of round-trip commission.
            eod_exit_time:  Time of day for forced end-of-day exit.
        """
        self.slippage = slippage_pts
        self.commission = commission_pts
        self.eod_exit_time = eod_exit_time

    def simulate(
        self,
        signals: List[AresSignal],
        candles_df: pd.DataFrame,
    ) -> List[CompletedTrade]:
        """
        Run the trade simulation across all signals against the candle history.
        
        Args:
            signals:    List of AresSignal objects generated by the backtest engine.
            candles_df: DataFrame with columns [timestamp, open, high, low, close, volume].
                        Must be sorted by timestamp ascending.
                        
        Returns:
            List of CompletedTrade objects for every resolved trade.
        """
        if candles_df.empty or not signals:
            return []

        trades: List[CompletedTrade] = []

        # Pre-convert timestamps to numpy array for fast lookup
        ts_array = candles_df["timestamp"].values

        for signal in signals:
            signal_ts = np.datetime64(signal.timestamp)

            # Find the index of the first candle AFTER the signal
            entry_idx = np.searchsorted(ts_array, signal_ts, side="right")
            if entry_idx >= len(candles_df):
                continue  # No candles after this signal

            entry_candle = candles_df.iloc[entry_idx]
            entry_price = float(entry_candle["open"])  # Enter on next candle's open

            # Apply slippage
            if signal.direction == Direction.BULLISH:
                entry_price += self.slippage
            else:
                entry_price -= self.slippage

            # Walk forward candle-by-candle to find exit
            trade = self._walk_to_exit(
                signal=signal,
                entry_price=entry_price,
                entry_time=pd.Timestamp(entry_candle["timestamp"]).to_pydatetime(),
                candles_df=candles_df,
                start_idx=entry_idx,
            )

            if trade:
                trades.append(trade)

        return trades

    def _walk_to_exit(
        self,
        signal: AresSignal,
        entry_price: float,
        entry_time: datetime,
        candles_df: pd.DataFrame,
        start_idx: int,
    ) -> Optional[CompletedTrade]:
        """
        Walk forward from entry to find the exit condition.
        
        Checks in order each candle:
          1. Stop-loss hit → exit
          2. Target-2 hit → exit (full exit at T2 for simplicity)
          3. Target-1 hit → exit
          4. End of day → forced close
        """
        is_bullish = signal.direction == Direction.BULLISH
        sl = signal.stop_loss
        t1 = signal.target_1
        t2 = signal.target_2

        peak_fav = 0.0
        peak_adv = 0.0
        entry_date = entry_time.date()

        for i in range(start_idx, len(candles_df)):
            row = candles_df.iloc[i]
            candle_ts = pd.Timestamp(row["timestamp"]).to_pydatetime()
            h = float(row["high"])
            l = float(row["low"])
            c = float(row["close"])

            # Track excursions
            if is_bullish:
                fav = h - entry_price
                adv = entry_price - l
            else:
                fav = entry_price - l
                adv = h - entry_price

            peak_fav = max(peak_fav, fav)
            peak_adv = max(peak_adv, adv)

            # ── Check SL first (worst case) ──────────────────────────────
            if is_bullish and l <= sl:
                return self._build_trade(
                    signal, entry_price, sl, "SL", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )
            if not is_bullish and h >= sl:
                return self._build_trade(
                    signal, entry_price, sl, "SL", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )

            # ── Check T2 (best case) ─────────────────────────────────────
            if is_bullish and h >= t2:
                return self._build_trade(
                    signal, entry_price, t2, "T2", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )
            if not is_bullish and l <= t2:
                return self._build_trade(
                    signal, entry_price, t2, "T2", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )

            # ── Check T1 ─────────────────────────────────────────────────
            if is_bullish and h >= t1:
                return self._build_trade(
                    signal, entry_price, t1, "T1", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )
            if not is_bullish and l <= t1:
                return self._build_trade(
                    signal, entry_price, t1, "T1", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )

            # ── End of day check ─────────────────────────────────────────
            if candle_ts.date() != entry_date or candle_ts.time() >= self.eod_exit_time:
                return self._build_trade(
                    signal, entry_price, c, "EOD", entry_time,
                    candle_ts, i - start_idx + 1, peak_fav, peak_adv, is_bullish
                )

        # If we exhausted all candles, close at last candle
        last = candles_df.iloc[-1]
        return self._build_trade(
            signal, entry_price, float(last["close"]), "EOD", entry_time,
            pd.Timestamp(last["timestamp"]).to_pydatetime(),
            len(candles_df) - start_idx, peak_fav, peak_adv, is_bullish
        )

    def _build_trade(
        self,
        signal: AresSignal,
        entry_price: float,
        exit_price: float,
        exit_reason: str,
        entry_time: datetime,
        exit_time: datetime,
        holding_candles: int,
        peak_fav: float,
        peak_adv: float,
        is_bullish: bool,
    ) -> CompletedTrade:
        """Construct a CompletedTrade with P&L calculation."""
        if is_bullish:
            pnl = exit_price - entry_price
        else:
            pnl = entry_price - exit_price

        pnl -= self.commission

        return CompletedTrade(
            signal=signal,
            entry_price=entry_price,
            exit_price=exit_price,
            exit_reason=exit_reason,
            pnl_points=round(pnl, 2),
            entry_time=entry_time,
            exit_time=exit_time,
            holding_candles=holding_candles,
            peak_favorable=round(peak_fav, 2),
            peak_adverse=round(peak_adv, 2),
        )
