from typing import List, Dict

from models import ResistanceLevel
from config import settings


class LevelFetcher:
    """
    LevelFetcher builds a list of key support and resistance levels for the NIFTY 50.
    
    Sources for levels:
    1. Static: Previous Day High (PDH) and Previous Day Low (PDL) - populated at session start.
    2. Dynamic: Option Interest (OI) walls extracted from the live option chain.
       - CE walls act as resistance (above spot).
       - PE walls act as support (below spot).
       
    These levels are fed into the FailedBreakoutDetector to see if price is interacting
    with a significant barrier.
    """

    def __init__(self):
        """
        Initialize the fetcher with default static levels.
        """
        self.prev_day_high: float = 0.0
        self.prev_day_low: float = 0.0

    def set_previous_day_levels(self, high: float, low: float) -> None:
        """
        Store the Previous Day High and Low.
        This should be called once at the beginning of the trading session.
        
        Args:
            high: Previous trading day's high price.
            low: Previous trading day's low price.
        """
        self.prev_day_high = high
        self.prev_day_low = low

    def build_levels(self, spot_price: float, full_chain: List[Dict], oi_wall_threshold: int) -> List[ResistanceLevel]:
        """
        Builds and returns a deduplicated, sorted list of ResistanceLevel objects based on
        PDH, PDL, and dynamic OI walls.
        
        Args:
            spot_price: The current NIFTY spot price.
            full_chain: The full option chain list generated by OIFetcher.
            oi_wall_threshold: The minimum OI to be considered a wall (from config).
            
        Returns:
            A list of ResistanceLevel objects sorted by price.
        """
        scan_range = settings.level_scan_range
        levels_map: Dict[float, ResistanceLevel] = {}

        # Helper to add a level, keeping the one with higher strength if prices clash
        def add_level(level: ResistanceLevel):
            if level.price in levels_map:
                if level.strength > levels_map[level.price].strength:
                    levels_map[level.price] = level
                # If equal strength, we could combine sources, but keeping the existing one is fine.
            else:
                levels_map[level.price] = level

        # 1. Add static levels (PDH / PDL)
        if self.prev_day_high > 0:
            add_level(ResistanceLevel(
                price=self.prev_day_high,
                source="prev_day_high",
                strength=3
            ))
            
        if self.prev_day_low > 0:
            add_level(ResistanceLevel(
                price=self.prev_day_low,
                source="prev_day_low",
                strength=3
            ))

        # 2. Add dynamic levels from the option chain
        for row in full_chain:
            strike = float(row["strike"])
            
            # Skip strikes outside our scan range
            if abs(strike - spot_price) > scan_range:
                continue

            # CE Walls (Resistance - usually above spot)
            if strike >= spot_price:
                ce_oi = row["ce_oi"]
                ce_oi_change_pct = row["ce_oi_change_pct"]
                
                if ce_oi > oi_wall_threshold and ce_oi_change_pct > settings.oi_wall_min_oi_change_pct:
                    strength = 2 if ce_oi > (oi_wall_threshold * 2) else 1
                    add_level(ResistanceLevel(
                        price=strike,
                        source="oi_wall_ce",
                        strength=strength
                    ))

            # PE Walls (Support - usually below spot)
            if strike <= spot_price:
                pe_oi = row["pe_oi"]
                pe_oi_change_pct = row["pe_oi_change_pct"]
                
                if pe_oi > oi_wall_threshold and pe_oi_change_pct > settings.oi_wall_min_oi_change_pct:
                    strength = 2 if pe_oi > (oi_wall_threshold * 2) else 1
                    add_level(ResistanceLevel(
                        price=strike,
                        source="oi_wall_pe",
                        strength=strength
                    ))

        # Deduplicated (handled by dict) and sorted by price
        sorted_levels = sorted(levels_map.values(), key=lambda lvl: lvl.price)
        
        return sorted_levels
